name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-12
    steps:
    - uses: rigor789/action-create-emulator@main
      with:
        package: 'system-images;android-32;default;x86'

