name: CI

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest
    steps:
    - uses: rigor789/action-create-emulator@master
      with:
        package: 'system-images;android-29;default;x86'

